exports.seed = async function (knex) {
  // Deletes ALL existing entries
  await knex("pets").del();
  await knex("pets").insert([
    {
      id: 1,
      pet_name: "Luna",
      pet_type: "Dog",
      owner_name: "Sarah",
      owner_contact: "204-555-1234",
      pet_location: "Yorkville, Toronto",
      pet_description: "Luna went missing chasing a squirrel",
      pet_image: "pets-01.png",
      pet_imgalt: "an image of Luna, a cute golden retriever",
      long: -79.3948,
      lati: 43.6706,
    },
    {
      id: 2,
      pet_name: "Liam",
      pet_type: "Dog",
      owner_name: "Amy",
      owner_contact: "310-555-5678",
      pet_location: "Liberty Village, Toronto",
      pet_description: "Liam went missing out of his leash",
      pet_image: "pets-02.png",
      pet_imgalt: "a cute image of Liam, a beagle dog",
      long: -79.4163,
      lati: 43.6391,
      finder_name: "Monica",
      finder_contact: "647-145-9855",
    },
    {
      id: 3,
      pet_name: "Bella",
      pet_type: "Cat",
      owner_name: "Emma",
      owner_contact: "415-555-2345",
      pet_location: "Downtown, Toronto",
      pet_description: "Bella went missing through an opened door",
      pet_image: "pets-03.png",
      pet_imgalt: "a cute image of Bella, an american shorthair cat",
      long: -79.3839,
      lati: 43.6511,
    },
    {
      id: 4,
      pet_name: "Snowball",
      pet_type: "Cat",
      owner_name: "Jim",
      owner_contact: "510-555-6789",
      pet_location: "Downtown, Toronto",
      pet_description: "Snowball went missing during Halloween",
      pet_image: "pets-04.png",
      pet_imgalt: "a picture of snowball, a cute cat",
      long: -79.3933,
      lati: 43.6508,
    },
    {
      id: 5,
      pet_name: "Buddy",
      pet_type: "Cat",
      owner_name: "Tom",
      owner_contact: "619-555-3456",
      pet_location: "Lakeside, Toronto",
      pet_description: "Buddy escaped her cage during a rainy night",
      pet_image: "pets-05.png",
      pet_imgalt: "a cute image of Buddy, a soft kitten",
      long: -79.3807,
      lati: 43.6394,
      finder_name: "Jessie",
      finder_contact: "647-987-0945",
    },
    {
      id: 6,
      pet_name: "Coco",
      pet_type: "Dog",
      owner_name: "Julia",
      owner_contact: "619-555-3527",
      pet_location: "Old Town, Toronto",
      pet_description: "Coco got scared during a storm and ran away",
      pet_image: "pets-06.png",
      pet_imgalt: "a cute image of coco, a furry puppy",
      long: -79.37,
      lati: 43.6503,
    },
    {
      id: 7,
      pet_name: "Charlie",
      pet_type: "Dog",
      owner_name: "Yoi",
      owner_contact: "714-555-4567",
      pet_location: "West End, Toronto",
      pet_description: "Charlie dug under the fence and went missing",
      pet_image: "pets-07.png",
      pet_imgalt: "a cute image of Charlie, a furry puppy running",
      long: -79.4637,
      lati: 43.6535,
    },
    {
      id: 8,
      pet_name: "Sunshine",
      pet_type: "Dog",
      owner_name: "Young",
      owner_contact: "604-555-8901",
      pet_location: "Downtown, Toronto",
      pet_description: "Sunshine went missing during a firework",
      pet_image: "pets-08.png",
      pet_imgalt: "a cute image of Sunshine, a golden puppy",
      long: -79.3957,
      lati: 43.6469,
    },
    {
      id: 9,
      pet_name: "Shadow",
      pet_type: "Cat",
      owner_name: "John",
      owner_contact: "647-555-5678",
      pet_location: "Sheppard Ave, North York",
      pet_description: "Shadow went missing through an opened window",
      pet_image: "pets-09.png",
      pet_imgalt: "a cute image of Shadow, a furry american shorthair cat",
      long: -79.4111,
      lati: 43.7615,
    },
    {
      id: 10,
      pet_name: "Ginger",
      pet_type: "Dog",
      owner_name: "Younha",
      owner_contact: "705-555-6789",
      pet_location: "Financial District, Toronto",
      pet_description: "Ginger went missing during a walk to lakeside",
      pet_image: "pets-10.png",
      pet_imgalt: "a cute image of Ginger, a golden retriever",
      long: -79.3871,
      lati: 43.6465,
    },
    {
      id: 11,
      pet_name: "Bagel",
      pet_type: "Dog",
      owner_name: "Loki",
      owner_contact: "780-555-9876",
      pet_location: "Midtown, Toronto",
      pet_description: "Bagel hopped out of the yard",
      pet_image: "pets-11.png",
      pet_imgalt: "a cute image of Bagel, a beagle dog",
      long: -79.3978,
      lati: 43.7044,
    },
    {
      id: 12,
      pet_name: "James",
      pet_type: "Dog",
      owner_name: "Ota",
      owner_contact: "902-555-4321",
      pet_location: "Entertainment District, Toronto",
      pet_description: "James went missing during a commissioned park walk",
      pet_image: "pets-12.png",
      pet_imgalt: "a cute image of James, a french bulldog",
      long: -79.3941,
      lati: 43.6448,
    },
  ]);
};
